docker run \
    --network host \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/main.py:/home/main.py \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/rollout.py:/home/rollout.py \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/ehr_gym:/home/ehr_gym \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/configs:/home/configs \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/data:/home/data \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/cache:/home/cache \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/workdir:/home/workdir \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/entrypoint.sh:/home/entrypoint.sh \
    -v <YOUR_PATH_TO_MEDAGENTGYM>/credentials.toml:/home/credentials.toml \
    -e TASK_NAME="biocoder" \
    -it ehr_gym:latest
